### PR TITLE
Dropdown scenario completed

### PR DESCRIPTION
**Pull request by chiragkhimani**

### CODE REVIEW

**Comment by guljahanJ** [comment]
Great!

**Comment by sebnem85** [comment]
Perfect!

**Review by Fidema — COMMENTED** [review]
excellent job!

**Review by guljahanJ — APPROVED** [review]

**Review by vildanembel — APPROVED** [review]

**Comment by Fidema** [comment]
excellent job!

**Review by AishaGench — APPROVED** [review]

**Review by Suatqa — APPROVED** [review]

**Pull request merged**
